# Generated by Django 5.1.1 on 2024-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_policy_customer_policy_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="customer@mail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
