# Generated by Django 5.1.1 on 2024-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="premium_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
    ]
