# Generated by Django 5.1.1 on 2024-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_policy_premium_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_number",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
