# Generated by Django 5.1.1 on 2024-09-12 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_policy_end_date_alter_policy_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
