# Generated by Django 5.1.1 on 2024-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_policy_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
    ]
